server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/fhir+json,application/fhir+xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: LifeLog
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/lifelog}
    redis:
      host: redis
      port: 6379
  security:
    admin:
      username: admin
      password: password
    clinical:
      username: clinician
      password: password

  fhir:
    server:
      base-path: /fhir/*

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,metrics
  endpoint:
    health:
      show-details: always
