server:
  port: 8080

spring:
  application:
    name: LifeLog
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/lifelog}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8180/realms/lifelog}

hapi:
  fhir:
    server:
      base-path: /fhir/*
